const data = [
  {
    name: "경묘당",
    adress: "수원",
    contact: "https://linktr.ee/seniorcatcenter",
    hoto: "네이버 카페 문의",
    volunteer: "개인 봉사 가능",
    access: "교통수단+ 택시 가능",
  },
  {
    name: "동물자유연대",
    adress: "경기",
    contact: "https://instagram.com/kawa.hq?utm_medium=copy_link",
    hoto: "이메일 신청으로 알고 있어요!",
    volunteerform: "개인 단체 모두 가능",
    access: "",
  },
  {
    name: "완주 늘봄 보호소",
    adress: "전북 완주군",
    contact: "전주시 동물복지과(063-281-5049)",
    hoto: "센터 연락처를 몰라서 개인 봉사 다니시는 분을 우연히 sns에서 알게돼 문의했어요",
    volunteerform: "개인 단체 모두 가능",
    access: "자차가 필요하거나 차량으로만 접근가능",
  },
  {
    name: "포천쉼터",
    adress: "경기",
    contact: "https://instagram.com/aerinwon1004?utm_medium=copy_link",
    hoto: "sns문의",
    volunteerform: "개인 단체 모두 가능",
    access: "택시도 가능해요",
  },
  {
    name: "동물권시민연대 RAY",
    adress: "서울 종로구",
    contact: "인스타그램 @ray_at_home",
    hoto: "sns문의",
    volunteerform: "개인 봉사 가능",
    access: "교통수단+ 택시 가능",
  },
];
